# Generated by Django 4.2.17 on 2024-12-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=None)),
                ('type', models.CharField(choices=[('greengorcer', 'greengorcer'), ('butcher shop', 'butcher shop'), ('condiment', 'condiment'), ('Bakery', 'Bakery'), ('Rice/Noodles', 'Rice/Noodles'), ('Other', 'Other')], default='Other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.product')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
